server:
  port: 8765


#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#  application:
#    name: api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: service-app
          uri: lb://SERVICE
          predicates:
            - Path=/api/v1/service/**
          filters:
            - AuthenticationFilter

        - id: billing-service
          uri: lb://PAYMENT
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
  application:
      name: api-gateway

